skip_branch_with_pr: true

build_script:
  - build/appveyor/build.cmd

artifacts:
  - path: build/cmake/build_win32_benchmark/Release/unreal_speccy_portable.exe 
    name: Unreal Speccy Portable benchmark
  - path: build/cmake/build_win32_sdl2/Release/unreal_speccy_portable.exe
    name: Unreal Speccy Portable sdl2 gles2 angle
